[project]
name = "nix-python-devenv"
version = "0.1.0"
description = "Example project with working C bindings!"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "onnx>=1.17.0",
    "onnxruntime>=1.19.2",
    "onnxsim>=0.4.36",
]
